apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtt-rest-api
  namespace: gtt
  labels:
    app: gtt-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtt-rest-api
  template:
    metadata:
      labels:
        app: gtt-rest-api
    spec:
      imagePullSecrets:
        - name: example_secret #INSERT_SECRET_NAME_HERE
      containers:
        - name: rest-api
          image: example_image_tag #INSERT_IMAGE_TAG_HERE
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 9090
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: 9090
