apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtt-rest-api-deploy
  labels:
    app: gtt-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gtt-rest-api
  template:
    metadata:
      labels:
        app: gtt-rest-api
    spec:
      imagePullSecrets:
        - name: example_secret #INSERT_SECRET_NAME_HERE
      containers:
        - name: gtt-rest-api
          image: example_image_tag #INSERT_IMAGE_TAG_HERE
