apiVersion: v1
kind: Service
metadata:
  name: gtt-rest-api-svc
  namespace: gtt
spec:
  type: ClusterIP
  selector:
    app: gtt-rest-api
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 9090