apiVersion: v1
kind: Service
metadata:
  name: gtt-rest-api-nodeport
  namespace: gtt
spec:
  type: NodePort
  selector:
    app: gtt-rest-api
  ports:
    - protocol: TCP
      nodePort: 30123
      port: 1234
      targetPort: 9090